---
- name: Install gitea to host localhost
  hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:
    - name: Ensure group "gitea" exists
      group:
        name: gitea
        state: present

    - name: Ensure user "gitea" exists
      user:
        name: gitea
        comment: Managed by Ansible.
        group: gitea
        shell: /bin/bash

    - name: install the latest version of git
      yum:
        name: git
        state: latest

    - name: Prepare folders for gitea /home/gitea/bin/
      file:
        path: "/home/gitea/bin/{{ item }}"
        state: directory
        owner: gitea
        group: gitea
        mode: 0750
      with_items: ["custom", "data", "indexers", "public", "log"]

    - name: Prepare folders for gitea /etc/gitea
      file:
        path: /etc/gitea
        state: directory
        owner: root
        group: gitea
        mode: 0770

    - name: Prepare folders for gitea /home/gitea/bin/custom/conf
      file:
        path: /home/gitea/bin/custom/conf
        state: directory
        owner: gitea
        group: gitea
        mode: 0750

    - name: Download gitea binary
      get_url:
        url: https://dl.gitea.io/gitea/1.5.0/gitea-1.5.0-linux-amd64
        dest: /home/gitea/bin/gitea
        mode: 0755

    - name: Copy prepared app.ini
      copy:
        owner: gitea
        group: gitea
        mode: 0755
        src: ./app.ini
        dest: /home/gitea/bin/custom/conf/app.ini

    - name: Create gitea service
      copy:
        owner: root
        group: root
        mode: 0755
        src: ./gitea.service
        dest: /etc/systemd/system/gitea.service

    - name: Start gitea service to create db
      systemd:
        enabled: yes
        state: started
        name: gitea
        daemon_reload: yes

    - name: sleep for 30 seconds to give enough time for db regeneration
      wait_for: timeout=30
      delegate_to: localhost

    - name: Stop gitea service to add user
      systemd:
        enabled: yes
        state: stopped
        name: gitea
        daemon_reload: yes

    - name: Add user to gitea
      shell: ./gitea admin create-user --name DevOps --password Start123! --email petermikaczo@gmail.com --admin
#todo - Insecure password. Ansible has own vault system to crypt / decrypt passwords. Please use it to make you playbook secure.
      args:
        chdir: "/home/gitea/bin/"
        executable: /bin/bash
      become: true
      become_user: gitea

    - name: Start configured gitea
      systemd:
        enabled: yes
        state: started
        name: gitea